t=tic;
[detX,fl0,rr0,it0,rv0]= pcg(J'*J,-J'*f,1e-10,200);
toc(t);
t=tic;
L = ichol(J'*J);
[x1,fl1,rr1,it1,rv1] = pcg(J'*J,J'*f,1e-8,100,L,L');
toc(t);
t=tic;
L = ichol(J'*J,struct('michol','on'));
[detX,fl2,rr2,it2,rv2]= pcg(J'*J,-J'*f,1e-10,200,L,L');
   toc(t);
figure;
semilogy(0:it0,rv0/norm(J'*f),'b.');
hold on;
semilogy(0:it1,rv1/norm(J'*f),'r.');
semilogy(0:it2,rv2/norm(J'*f),'k.');
legend('No Preconditioner','IC(0)','MIC(0)');
xlabel('iteration number');
ylabel('relative residual');
hold off;